config1 = {
    "num_actions": 3,
    "num_states": 10*3*2,
    "grid_size": 50,
    "num_ants": 100,
    "num_food_sources": 5,
    "max_food_per_source": 100,
    "learning_rate": 0.001,
    "gamma": 0.8,
    "epsilon": 0.9,
    "num_agents": 100,
}
config2 = {
    "num_actions": 3,
    "num_states": 10*3*2,
    "grid_size": 50,
    "num_ants": 10,
    "num_food_sources": 10,
    "max_food_per_source": 25,
    "learning_rate": 0.05,
    "gamma": 0.95,
    "epsilon": 0.1,
    "num_agents": 10,
}
config3 = {
    "num_actions": 3,
    "num_states": 10*3*2,
    "grid_size": 50,
    "num_ants": 30,
    "num_food_sources": 5,
    "max_food_per_source": 100,
    "learning_rate": 0.01,
    "gamma": 0.5,
    "epsilon": 0.3,
    "num_agents": 30,
}

config4 = {
    "num_actions": 3,
    "num_states": 10*3*2,
    "grid_size": 50,
    "num_ants": 20,
    "num_food_sources": 3,
    "max_food_per_source": 100,
    "learning_rate": 0.01,
    "gamma": 0.8,
    "epsilon": 0.8,
    "num_agents": 20,
}
config5 = {
    "num_actions": 3,
    "num_states": 10*3*2,
    "grid_size": 60,
    "num_ants": 100,
    "num_food_sources": 4,
    "max_food_per_source": 100,
    "learning_rate": 0.1,
    "gamma": 0.5,
    "epsilon": 0.995,
    "num_agents": 100,
}
